/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

// Esta playlist de youtube fue de mucha ayuda para poder hacer el programa, nos pudimos guiar con algunos de los los codigos usados en los videos para hacer el trabajo mas ameno.
//https://www.youtube.com/watch?v=0a_Y2itvK_I&list=PL-Mlm_HYjCo_uketceEXL4CuoPf9t38FZ&index=1&ab_channel=C%C3%B3digosdeProgramaci%C3%B3n
public class Vista_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Vista_Inicio() {

        initComponents();
        this.setLocationRelativeTo(null); // Metodo para que la ventana se abra al medio de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        btncerrar = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();
        txtcontraseña = new javax.swing.JPasswordField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel5.setText("Vendedor");

        lblusuario.setText("Usuario:");

        lblcontraseña.setText("Contraseña: ");

        btncerrar.setText("Cancelar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btnsiguiente.setText("Siguiente");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusuario)
                    .addComponent(lblcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(txtcontraseña))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 184, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(183, 183, 183))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btncerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsiguiente)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuario)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontraseña)
                    .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncerrar)
                    .addComponent(btnsiguiente))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        String Usuario = "Sebastian Gutierrez"; // Creacion de nuestros usuarios y contraseñas para poder ingresar a la base de datos
        String Contraseña = "200806891";
        String Usuario2 = "Claudio Salazar";
        String Contraseña2 = "200804147";
        String Usuario3 = "Misael Godoi";
        String Contraseña3 = "185816664";
        String Usuario4 = "Christian Topp";
        String Contraseña4 = "198103756";

        String Contra = new String(txtcontraseña.getPassword()); //Creamos una contraseña tipo string que va a ser igual a la contraseña que nosotros tipiemos en la ventana.

        if (txtusuario.getText().equals(Usuario) && Contra.equals(Contraseña)) { // Si el usuario y contraseña ingresado en la ventana son iguales a los creados anteriormente. 
            Vista_BD BD = new Vista_BD();//creamos nuestra ventana de la base de datos.
            BD.setVisible(true);// se abre nuestra ventana base de datos.
            dispose();// y se cierra esta ventana login.
        } else {
            if (txtusuario.getText().equals(Usuario2) && Contra.equals(Contraseña2)) {// Si el usuario y contraseña ingresado en la ventana son iguales a los creados anteriormente. 
                Vista_BD BD = new Vista_BD();//creamos nuestra ventana de la base de datos.
                BD.setVisible(true);// se abre nuestra ventana base de datos.
                dispose();// y se cierra esta ventana login.

            } else {
                if (txtusuario.getText().equals(Usuario3) && Contra.equals(Contraseña3)) {// Si el usuario y contraseña ingresado en la ventana son iguales a los creados anteriormente.
                    Vista_BD BD = new Vista_BD();//creamos nuestra ventana de la base de datos.
                    BD.setVisible(true);// se abre nuestra ventana base de datos.
                    dispose();// y se cierra esta ventana login.

                } else {
                    if (txtusuario.getText().equals(Usuario4) && Contra.equals(Contraseña4)) {// Si el usuario y contraseña ingresado en la ventana son iguales a los creados anteriormente.
                        Vista_BD BD = new Vista_BD();//creamos nuestra ventana de la base de datos.
                        BD.setVisible(true);// se abre nuestra ventana base de datos.
                        dispose();// y se cierra esta ventana login.
                    } else {
                        JOptionPane.showMessageDialog(this, "Datos Incorrectos, intente de nuevo"); //Si los datos son incorrectos, un optionpane nos dira que lo intentemos de nuevo.

                    }
                }

            }
        }


    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        dispose();//Si presionamos el boton cerrar, se cierra la ventana.
    }//GEN-LAST:event_btncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("WINDOWS".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
